import { LabValueCategory } from "./types"

export const LAB_VALUES_DATA: LabValueCategory[] = [
  {
    id: "gaz-du-sang",
    name: "Gaz du sang",
    values: [
      {
        id: "ph",
        name: "pH",
        usValue: "7,35-7,45",
        siValue: "7,35-7,45",
        usUnit: "",
        siUnit: "",
      },
      {
        id: "pco2",
        name: "PCO₂",
        usValue: "35-45",
        siValue: "4,7-6,0",
        usUnit: "mm Hg",
        siUnit: "kPa",
      },
      {
        id: "po2",
        name: "PO₂",
        usValue: "80-105",
        siValue: "10,6-14",
        usUnit: "mm Hg",
        siUnit: "kPa",
      },
    ],
  },
  {
    id: "electrolytes",
    name: "Électrolytes",
    values: [
      {
        id: "bicarbonate",
        name: "Bicarbonate",
        usValue: "22-28",
        siValue: "22-28",
        usUnit: "mEq/L",
        siUnit: "mmol/L",
      },
      {
        id: "calcium",
        name: "Calcium",
        usValue: "8,4-10,2",
        siValue: "2,1-2,5",
        usUnit: "mg/dL",
        siUnit: "mmol/L",
      },
      {
        id: "chlorure",
        name: "Chlorure",
        usValue: "95-106",
        siValue: "95-106",
        usUnit: "mEq/L",
        siUnit: "mmol/L",
      },
      {
        id: "magnesium",
        name: "Magnésium",
        usValue: "1,3-2,1",
        siValue: "0,65-1,05",
        usUnit: "mEq/L",
        siUnit: "mmol/L",
      },
      {
        id: "phosphate",
        name: "Phosphate",
        usValue: "2,7-4,5",
        siValue: "0,87-1,45",
        usUnit: "mg/dL",
        siUnit: "mmol/L",
      },
      {
        id: "potassium",
        name: "Potassium",
        usValue: "3,5-5,0",
        siValue: "3,5-5,0",
        usUnit: "mEq/L",
        siUnit: "mmol/L",
      },
      {
        id: "sodium",
        name: "Sodium",
        usValue: "136-145",
        siValue: "136-145",
        usUnit: "mEq/L",
        siUnit: "mmol/L",
      },
    ],
  },
  {
    id: "biochimie",
    name: "Biochimie",
    values: [
      {
        id: "albumine",
        name: "Albumine",
        usValue: "3,5-5,0",
        siValue: "35-50",
        usUnit: "g/dL",
        siUnit: "g/L",
      },
      {
        id: "alp",
        name: "ALP",
        usValue: "35-100",
        siValue: "35-100",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "alt",
        name: "ALT",
        usValue: "8-20",
        siValue: "8-20",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "amylase",
        name: "Amylase",
        usValue: "25-125",
        siValue: "25-125",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "ast",
        name: "AST",
        usValue: "8-20",
        siValue: "8-20",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "bilirubine-directe",
        name: "Bilirubine (directe)",
        usValue: "0-0,3",
        siValue: "0-5",
        usUnit: "mg/dL",
        siUnit: "µmol/L",
      },
      {
        id: "bilirubine-totale",
        name: "Bilirubine (totale)",
        usValue: "0,1-1,0",
        siValue: "2-17",
        usUnit: "mg/dL",
        siUnit: "µmol/L",
      },
      {
        id: "uree",
        name: "Urée",
        usValue: "7-18",
        siValue: "2,5-7,1",
        usUnit: "mg/dL",
        siUnit: "mmol/L",
      },
      {
        id: "cholesterol",
        name: "Cholestérol",
        usValue: "<200",
        siValue: "<5,2",
        usUnit: "mg/dL",
        siUnit: "mmol/L",
      },
      {
        id: "creatinine-femme",
        name: "Créatinine (femme)",
        usValue: "10-70",
        siValue: "10-70",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "creatinine-homme",
        name: "Créatinine (homme)",
        usValue: "25-90",
        siValue: "25-90",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "ck-mb",
        name: "Créatine Kinase-MB",
        usValue: "0-12",
        siValue: "0-12",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "ferritine-femme",
        name: "Ferritine (femme)",
        usValue: "12-150",
        siValue: "12-150",
        usUnit: "ng/mL",
        siUnit: "µg/L",
      },
      {
        id: "ferritine-homme",
        name: "Ferritine (homme)",
        usValue: "15-200",
        siValue: "15-200",
        usUnit: "ng/mL",
        siUnit: "µg/L",
      },
      {
        id: "glycemie",
        name: "Glycémie (à jeun)",
        usValue: "70-110",
        siValue: "3,8-6,1",
        usUnit: "mg/dL",
        siUnit: "mmol/L",
      },
      {
        id: "hba1c",
        name: "HbA1c",
        usValue: "<6%",
        siValue: "<0,06",
        usUnit: "",
        siUnit: "",
      },
      {
        id: "ldh",
        name: "LDH",
        usValue: "100-250",
        siValue: "100-250",
        usUnit: "U/L",
        siUnit: "U/L",
      },
      {
        id: "osmolalite",
        name: "Osmolalité",
        usValue: "275-300",
        siValue: "275-300",
        usUnit: "mOsm/kg",
        siUnit: "mOsm/kg",
      },
    ],
  },
  {
    id: "hormones",
    name: "Hormones",
    values: [
      {
        id: "acth",
        name: "ACTH (0800h)",
        usValue: "<60",
        siValue: "<13,2",
        usUnit: "pg/mL",
        siUnit: "pmol/L",
      },
      {
        id: "cortisol",
        name: "Cortisol (0800h)",
        usValue: "5-23",
        siValue: "138-635",
        usUnit: "µg/dL",
        siUnit: "nmol/L",
      },
      {
        id: "prolactine",
        name: "Prolactine",
        usValue: "<20",
        siValue: "<20",
        usUnit: "ng/mL",
        siUnit: "ng/mL",
      },
      {
        id: "testosterone",
        name: "Testostérone (homme, libre)",
        usValue: "9-30",
        siValue: "0,31-1",
        usUnit: "ng/dL",
        siUnit: "pmol/L",
      },
      {
        id: "t4",
        name: "Thyroxine (T4)",
        usValue: "5-12",
        siValue: "64-155",
        usUnit: "ng/dL",
        siUnit: "nmol/L",
      },
      {
        id: "t3",
        name: "Triiodothyronine (T3)",
        usValue: "115-190",
        siValue: "1,8-2,9",
        usUnit: "ng/dL",
        siUnit: "nmol/L",
      },
      {
        id: "tsh",
        name: "TSH",
        usValue: "0,5-5",
        siValue: "0,5-5",
        usUnit: "µU/mL",
        siUnit: "µU/mL",
      },
    ],
  },
  {
    id: "hematologie",
    name: "Hématologie",
    values: [
      {
        id: "vs-femme",
        name: "VS (femme)",
        usValue: "0-20",
        siValue: "0-20",
        usUnit: "mm/h",
        siUnit: "mm/h",
      },
      {
        id: "vs-homme",
        name: "VS (homme)",
        usValue: "0-15",
        siValue: "0-15",
        usUnit: "mm/h",
        siUnit: "mm/h",
      },
      {
        id: "hemoglobine-femme",
        name: "Hémoglobine (femme)",
        usValue: "12,3-15,7",
        siValue: "123-157",
        usUnit: "g/dL",
        siUnit: "g/L",
      },
      {
        id: "hemoglobine-homme",
        name: "Hémoglobine (homme)",
        usValue: "13,5-17,5",
        siValue: "140-174",
        usUnit: "g/dL",
        siUnit: "g/L",
      },
      {
        id: "hematocrite-femme",
        name: "Hématocrite (femme)",
        usValue: "36-46%",
        siValue: "36-46%",
        usUnit: "",
        siUnit: "",
      },
      {
        id: "hematocrite-homme",
        name: "Hématocrite (homme)",
        usValue: "41-53%",
        siValue: "41-53%",
        usUnit: "",
        siUnit: "",
      },
      {
        id: "inr",
        name: "INR",
        usValue: "1,0-1,14",
        siValue: "1,0-1,14",
        usUnit: "",
        siUnit: "",
      },
      {
        id: "leucocytes",
        name: "Leucocytes",
        usValue: "5-11×10³",
        siValue: "5-11×10⁹",
        usUnit: "cells/mm³",
        siUnit: "cells/L",
      },
      {
        id: "mcv",
        name: "MCV",
        usValue: "88-100",
        siValue: "88-100",
        usUnit: "µm³",
        siUnit: "fL",
      },
      {
        id: "plaquettes",
        name: "Plaquettes",
        usValue: "150-400×10³",
        siValue: "150-400×10⁹",
        usUnit: "/mm³",
        siUnit: "/L",
      },
      {
        id: "ptt",
        name: "PTT",
        usValue: "25-35",
        siValue: "25-35",
        usUnit: "s",
        siUnit: "s",
      },
      {
        id: "reticulocytes",
        name: "Réticulocytes",
        usValue: "0,5-1,5%",
        siValue: "20-84×10⁹",
        usUnit: "des GR",
        siUnit: "/L",
      },
    ],
  },
]
